repos:
  - repo: local
    hooks:
      - id: make-format
        name: Make Format
        entry: make format
        language: system
        pass_filenames: false
        types: [python]
      
      - id: make-lint
        name: Make Lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [python]
